### ISSUE TITLE
Switch Database Modules

### ISSUE THREAD

**Issue by CelestialCrafter** [Rexogamer/cytrus-re#16]
Enmap takes up lots of ram/cpu usage, and is basicly just a map, not a database. Keyv is Fast, Promise Based, and Efficient.

**Comment by CelestialCrafter** [comment]
https://www.npmjs.com/package/keyv

**Comment by Rexogamer** [comment]
we’ll do this at some point, not high priority

**Comment by Midou36O** [comment]
Where this is located?

**Comment by CelestialCrafter** [comment]
> Where this is located?

app.js and other files that require a database like: commands/configure.js it has Enmap in it/client.databasename

**Comment by Rexogamer** [comment]
note: app.js is cybase.js

but yeah get to it

**Comment by CelestialCrafter** [comment]
> note: app.js is cybase.js
> 
> but yeah get to it

oops forgot

**Comment by Rexogamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [switch from enmap to keyv](https://trello.com/c/AmLP0wum/1-switch-from-enmap-to-keyv)

**Comment by Midou36O** [comment]
it's updated in the beta branch (idk how to reference the commit i made lol)
anyway closing the issue unless something wrong goes with the bot's code
