### ISSUE TITLE
d.js v12 breaking bot

### ISSUE THREAD

**Issue by pika32223** [Rexogamer/cytrus-re#230]
Hey. Not sure if you are aware but discord.js released v12 and alot of changed. you should maybe update the code here as some may be outdated. discord.RichEmbed and such is no longer a thing and should be fixed here. let me know if you need the full changelog about the update.

**Comment by Rexogamer** [comment]
Thanks for opening this issue. We’re aware of this and at some point we’ll fix it up :)

**Comment by pika32223** [comment]
alright. Thanks for getting back with me!
