### ISSUE TITLE
client.logger.error(err); doesn't work on some OS

### ISSUE THREAD

**Issue by VenkSociety** [Rexogamer/cytrus-re#332]
A couple of people using non-Windows OS have encountered this error or something similar when using my bot:
http://prntscr.com/sv49j8

Also, this might be unrelated, but for some reason the bot goes offline for like a second and forces this error http://prntscr.com/sv4a4o

Most definitely a problem with the web-server for the dashboard.

**Comment by Rexogamer** [comment]
Just out of curiosity (not a fix), but have you been modifying the code at all?

**Comment by VenkSociety** [comment]
I use some aspects of the bot in my bot though for the most part, it's just using your code as a base.

**Comment by VenkSociety** [comment]
Using `console.error()` instead fixed it.

**Comment by Rexogamer** [comment]
Good to know.
