### ISSUE TITLE
Sending a message to the bot in DM crashes the bot

### ISSUE THREAD

**Issue by VenkSociety** [Rexogamer/cytrus-re#44]
`TypeError: Cannot read property 'id' of undefined
    at module.exports (C:\Users\----\Desktop\cytrus-re-master\events\channelCreate.js:5:51)`

**Comment by Rexogamer** [comment]
No sight of this file in the repository which is odd

**Comment by Rexogamer** [comment]
Question: are you using the latest version of the code?

**Comment by Rexogamer** [comment]
Can you give more info? Did you edit any code?

**Comment by VenkSociety** [comment]
Problem seems to have been due to Discord.js' "interesting" style. Apparently when you send a message in a DM, it counts it as "creating a channel". I was checking for guild options in the channelCreate event but not checking if in a DM first.
