### ISSUE TITLE
Add ability to submit people to be added to the global ban list

### ISSUE THREAD

**Issue by Rexogamer** [Rexogamer/cytrus-re#5]
We should add a command where people can submit users they think should be on the Global Ban List. It’d basically work like `cyre.bug`. We’d review it, and if we think they should be on the list, we edit the `GlobalBans.json` file.

**Comment by DestroyedEDGE** [comment]
solved with commit 829c6b9

**Comment by Oxygemo** [comment]
if in the future, and we're done with the bot and someone else gets the bot, can't this be used for bias?
