### ISSUE TITLE
'src' folder

### ISSUE THREAD

**Issue by DestroyedEDGE** [Rexogamer/cytrus-re#84]
the bot doesnt actually check for anything in '/src/commands/' so we should probably fix that before moving everything.

**Comment by Rexogamer** [comment]
we also need to do something about the `error-unification` stuff

**Comment by DestroyedEDGE** [comment]
is there even a reason that you want to move everything into a subdirectory

**Comment by Rexogamer** [comment]
yes, because it’s cleaner ueu
