### ISSUE TITLE
logger megathread

### ISSUE THREAD

**Issue by DestroyedEDGE** [Rexogamer/cytrus-re#86]
currently the logger is extremely buggy and crashes for seemingly no reason
we should really fix this

**Comment by Rexogamer** [comment]
known issues: 
- logger crashes the bot when it is added to a server

**Comment by DestroyedEDGE** [comment]
> 
> 
> known issues:
> 
>     * logger crashes the bot when it is added to a server

thats what i thought but it could be something else causing the crash
last time i joined it to a server it only crashed when i kicked it

**Comment by DestroyedEDGE** [comment]
alright so its not the logger's fault
its actually a problem with a required module not existing
ive pushed a temp fix to cytrus-re:djs12

**Comment by DestroyedEDGE** [comment]
Resolved with 3e75677
